export const blackPieces = [
  {
    type: "king",
    color: "black",
    position: { num: 8, letter: "e" },
    movementDirection: [
      "up",
      "down",
      "right",
      "left",
      "diagLeftUp",
      "diagLeftDown",
      "diagRightUp",
      "diagRightDown",
    ],
    range: 1,
    firstMove: true,
  },
  {
    type: "queen",
    color: "black",
    position: { num: 8, letter: "d" },
    movementDirection: [
      "up",
      "down",
      "right",
      "left",
      "diagLeftUp",
      "diagLeftDown",
      "diagRightUp",
      "diagRightDown",
    ],
    range: 8,
  },
  {
    type: "bishop1",
    color: "black",
    position: { num: 8, letter: "c" },
    movementDirection: [
      "diagLeftUp",
      "diagLeftDown",
      "diagRightUp",
      "diagRightDown",
    ],
    range: 8,
  },
  {
    type: "bishop2",
    color: "black",
    position: { num: 8, letter: "f" },
    movementDirection: [
      "diagLeftUp",
      "diagLeftDown",
      "diagRightUp",
      "diagRightDown",
    ],
    range: 8,
  },
  {
    type: "knight1",
    color: "black",
    position: { num: 8, letter: "b" },
    movementDirection: [
      "oneOclock",
      "twoOclock",
      "fourOclock",
      "fiveOclock",
      "sevenOclock",
      "eightOclock",
      "tenOclock",
      "elevenOclock",
    ],
    range: 1,
  },
  {
    type: "knight2",
    color: "black",
    position: { num: 8, letter: "g" },
    movementDirection: [
      "oneOclock",
      "twoOclock",
      "fourOclock",
      "fiveOclock",
      "sevenOclock",
      "eightOclock",
      "tenOclock",
      "elevenOclock",
    ],
    range: 1,
  },
  {
    type: "rook1",
    color: "black",
    position: { num: 8, letter: "a" },
    movementDirection: ["up", "down", "right", "left"],
    range: 8,
    firstMove: true,
  },
  {
    type: "rook2",
    color: "black",
    position: { num: 8, letter: "h" },
    movementDirection: ["up", "down", "right", "left"],
    range: 8,
    firstMove: true,
  },
  {
    type: "pawn1",
    color: "black",
    position: { num: 7, letter: "a" },
    movementDirection: ["down", "diagLeftDown", "diagRightDown"],
    range: 1,
    firstMove: true,
  },
  {
    type: "pawn2",
    color: "black",
    position: { num: 7, letter: "b" },
    movementDirection: ["down", "diagLeftDown", "diagRightDown"],
    range: 1,
    firstMove: true,
  },
  {
    type: "pawn3",
    color: "black",
    position: { num: 7, letter: "c" },
    movementDirection: ["down", "diagLeftDown", "diagRightDown"],
    range: 1,
    firstMove: true,
  },
  {
    type: "pawn4",
    color: "black",
    position: { num: 7, letter: "d" },
    movementDirection: ["down", "diagLeftDown", "diagRightDown"],
    range: 1,
    firstMove: true,
  },
  {
    type: "pawn5",
    color: "black",
    position: { num: 7, letter: "e" },
    movementDirection: ["down", "diagLeftDown", "diagRightDown"],
    range: 1,
    firstMove: true,
  },
  {
    type: "pawn6",
    color: "black",
    position: { num: 7, letter: "f" },
    movementDirection: ["down", "diagLeftDown", "diagRightDown"],
    range: 1,
    firstMove: true,
  },
  {
    type: "pawn7",
    color: "black",
    position: { num: 7, letter: "g" },
    movementDirection: ["down", "diagLeftDown", "diagRightDown"],
    range: 1,
    firstMove: true,
  },
  {
    type: "pawn8",
    color: "black",
    position: { num: 7, letter: "h" },
    movementDirection: ["down", "diagLeftDown", "diagRightDown"],
    range: 1,
    firstMove: true,
  },
];
