export const blackPieces = [
  { type: "king", color: "black", position: { num: 8, letter: "e" } },
  { type: "queen", color: "black", position: { num: 8, letter: "d" } },
  { type: "bishop1", color: "black", position: { num: 8, letter: "c" } },
  { type: "bishop2", color: "black", position: { num: 8, letter: "f" } },
  { type: "knight1", color: "black", position: { num: 8, letter: "b" } },
  { type: "knight2", color: "black", position: { num: 8, letter: "g" } },
  { type: "rook1", color: "black", position: { num: 8, letter: "a" } },
  { type: "rook2", color: "black", position: { num: 8, letter: "h" } },
  { type: "pawn1", color: "black", position: { num: 7, letter: "a" } },
  { type: "pawn2", color: "black", position: { num: 7, letter: "b" } },
  { type: "pawn3", color: "black", position: { num: 7, letter: "c" } },
  { type: "pawn4", color: "black", position: { num: 7, letter: "d" } },
  { type: "pawn5", color: "black", position: { num: 7, letter: "e" } },
  { type: "pawn6", color: "black", position: { num: 7, letter: "f" } },
  { type: "pawn7", color: "black", position: { num: 7, letter: "g" } },
  { type: "pawn8", color: "black", position: { num: 7, letter: "h" } },
];
